services:
  backend:
    build:
      context: ./backend
    ports:
      - "30011:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_KEY=${PERPLEXITY_KEY}
      - WEB_URL=${WEB_URL}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "30012:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}