services:
  backend:
    build:
      context: ./backend
    ports:
      - "30011:8000"
    volumes:
      - ./backend:/app  # Optional: For development
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "30012:3000"
    volumes:
      - ./webapp:/webapp
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL}