services:
  backend:
    build:
      context: ./backend
    ports:
      - "30011:8000"
    volumes:
      - ./backend:/app  # Optional: For development
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_KEY=${PERPLEXITY_KEY}
      - WEB_URL=${WEB_URL}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "30012:3000"
    volumes:
      - ./webapp:/webapp
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}